spring.application.name=teamplatform
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/teamplatform?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=8163
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

mybatis.configuration.map-underscore-to-camel-case=true
mybatis.type-aliases-package=com.zjgsu.teamplatform.entity

logging.level.com.zjgsu.teamplatform.mapper=debug

# actuator — 将 /health 映射到actuator，//供容器健康检查
management.endpoints.web.base-path=/actuator
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoints.web.path-mapping.health=always 

management.metrics.export.prometheus.enabled=true
management.metrics.tags.application=teamplatform
management.metrics.distribution.percentiles-histogram.http.server.requests=true
